version: '3.7'

volumes:
  postgres:

services:
  postgres:
    container_name: bmstu_db_postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
        - postgres:/var/lib/postgresql/data
        - ../lab01/csv:/csv
    ports:
        - 5432:5432
    networks:
        - my_persistent_network

networks:
  my_persistent_network:
    driver: bridge
